### ISSUE TITLE
Tree-shaking seems to be broken

### ISSUE THREAD

**Issue by austenpayan** [feathericons/react-feather#6] opened 2017-11-14 16:15 UTC
Running webpack bundle analyzer, I am seeing every icon being included in my minified bundles:
<img width="494" alt="screen shot 2017-11-14 at 8 11 56 am" src="https://user-images.githubusercontent.com/3936068/32790591-b2081bd2-c913-11e7-8d80-72084a05abc6.png">

Not sure if I am doing something wrong of if there is a problem in the package.

babelrc settings: 
```
{
    "presets": [
        ["env", {
            "loose": true,
            "modules": false
        }], "react"
    ],
    plugins: [
        'syntax-dynamic-import',
        'transform-object-rest-spread',
        'transform-class-properties'
    ]
}
```

**Comment by austenpayan** [comment] 2017-11-14 16:15
I am using import statements as well.

**Comment by SuperOleg39** [comment] 2017-11-22 12:05
Same problem, but i use TypeScript without Babel.

**Comment by cichelero** [comment] 2018-01-24 15:52
I had this problem too, and sent a pull request #10 describing @SuperOleg39 solution.

**Comment by johnunclesam** [comment] 2018-04-15 23:51
This is still broken.

I'm using it like this:

`import { Users } from "react-feather";`

But in analyze I see this:

![image](https://user-images.githubusercontent.com/21275217/38784862-95635f5a-4118-11e8-8d2e-84fea0e0eb7f.png)

I'm using `create-react-app` latest default.

Something broken?

**Comment by cichelero** [comment] 2018-04-16 09:05
This will always be the case untill this project is using babel to build ES modules into module.exports. It happens because WebPack only does tree shaking from ES modules. You can read it [here](https://webpack.js.org/guides/tree-shaking/).

You will need to import using the full path like described above.

**Comment by johnunclesam** [comment] 2018-04-16 10:09
Ok. I understand. Can I follow this thread for updates to when ES modules will be there? There is a PR?

**Comment by alex996** [comment] 2018-09-03 17:07
@RinkAttendant6 I don't see how it will help because the library is still transpiling ES modules to CommonJS, thereby making it hard to tree shake. It's not only Webpack that suffers from this, but also Rollup, which is geared towards ES modules as well.

If we were to go with ESM, we'd not only need `"sideEffects": false` but also `"modules": false` in `.babelrc`. But then anyone using Node would either need to transpile ESM to CJS themselves, or introduce a bundler to their build step. Coincidentally, many people already bundle their React server-rendered code, just as they have to their front-end. So I think this change would be welcomed, and IMO this is the most viable way to go forward. @cichelero What are your thoughts?

Other prospects are dim. We could ship two bundles, both CJS and ESM, but this will double the size, and put us at risk of timeout when installing the package. We could also publish `react-feather-es`, just like `lodash-es` did, but this would inevitably lead to duplication. End users would need to alias the library or force-rewrite the import path in their bundler config, which is doable, but hacky.

Just throwing out ideas. On the same note, has anyone tried `webpack-common-shake` to shake these icons?

**Comment by RinkAttendant6** [comment] 2018-09-04 11:55
@alex996 What about referencing the ESM file from the `module` field in `package.json`? From https://rollupjs.org/guide/en#tree-shaking:

> If your package.json file also has a module field, ES6-aware tools like Rollup and webpack 2+ will [import the ES6 module version](https://github.com/rollup/rollup/wiki/pkg.module) directly.

And it looks like Webpack prefers the `module` field over the `main` field in the [default `mainFields` configuration](https://webpack.js.org/configuration/resolve/#resolve-mainfields).

I don't have experience in publishing a library to npm, just trying to throw out some ideas here. If it comes to shipping two bundles, I don't really see that as problematic as long as the size of the final output doesn't increase (it shouldn't, because either the CJS or ESM would be considered depending on the build toolchain, not both.)

**Comment by lili21** [comment] 2018-09-05 04:05
@RinkAttendant6 You're right.

**Comment by sirugh** [comment] 2019-01-08 20:48
@notflip Yes. I think there was an open PR but it hasn't been merged.

**Comment by dallas** [comment] 2019-04-04 22:06
Might be worth looking at [Styled Icons](https://github.com/jacobwgillespie/styled-icons). They boast:

> styled-icons provides the Font Awesome, Feather, Icomoon, Material Design, Octicons, Typicons, Crypto Icons and Boxicons icon packs as Styled Components, with full support for TypeScript types and tree-shaking / ES modules.

**Comment by carmelopullara** [comment] 2019-07-04 10:24
Version 2.0.1 is out, with all the latest icons and support for tree-shaking.

**Closed by carmelopullara** 2019-07-04 10:24 UTC

**Comment by sarahdayan** [comment] 2020-08-15 00:12
@carmelopullara I'm using `2.0.8` and I still seem to have the issue.

![Capture d’écran 2020-08-15 à 02 09 27](https://user-images.githubusercontent.com/5370675/90300758-60e36080-de9c-11ea-978d-183c8ad785e3.png)

I'm using ES imports (reexports, not full paths) within a CRA app.

**Comment by damianobarbati** [comment] 2020-08-17 13:44
@carmelopullara I don't see the tree-shaking working properly with es imports:
```javascript
import { Download, Trash2, Copy } from 'react-feather';
```

All library ends up in the bundle.
What's the intended way to use the lib?

**Comment by nedtwigg** [comment] 2020-09-11 07:22
I believe this is still broken as of `2.0.8`.  I switched to [react-icons](https://github.com/react-icons/react-icons), and it fixed the tree shaking.  I'd rather use this library though, react-icons seems to bring more functionality than I want.

**Comment by sirugh** [comment] 2020-09-11 13:27
If ya'll are experiencing a regression in functionality I would recommend using codesandbox to reproduce the issue that way you can provide a working link to show the example. Probably want to do something with webpack bundle analyzer or something.

**Comment by alex996** [comment] 2020-09-11 17:04
The basic `webpack` + `babel` (`.js`) or `webpack` + `typescript` (`.tsx`) seems to tree shake just fine. I was suspicious that the `forwardRef` wrapper, combined with both `propTypes` and `displayName` assignment, might be breaking compression in `terser`, but it's not! So, something is probably not right in your webpack config.

To lib authors: consider using [oliviertassinari/babel-plugin-transform-react-remove-prop-types](oliviertassinari/babel-plugin-transform-react-remove-prop-types) to strip prop types in production. It's generally a good practice in React and can make or break tree shaking (see terser/terser#293). _I don't believe it's causing any issues here_, but it still is a safety net.

**Comment by nedtwigg** [comment] 2020-09-11 19:35
Love the icons, totally possible that my config is wrong, and I don't expect anyone to spend their time debugging my personal issue.  But just switching to react-icons, with no other changes, reduced by bundle size by ~250kb (see commit above).  I shrunk my build down to [this reproducible example](https://github.com/nedtwigg/react-feather-bundle-debug), `npx webpack` and you'll see this:

![image](https://user-images.githubusercontent.com/2924992/92965686-11586c00-f42b-11ea-8c2b-c20506cd8c9c.png)

- https://github.com/nedtwigg/react-feather-bundle-debug/blob/master/webpack.config.js
- https://github.com/nedtwigg/react-feather-bundle-debug/blob/master/tsconfig.json

**Comment by alex996** [comment] 2020-09-12 03:05
@nedtwigg You need to change the following lines in `tsconfig.json`:

```diff
-"module": "commonjs",
+"module": "esnext",
+moduleResolution": "node",
```
Check out the size before `409054 B` and after `27987 B`.

Basically, with `commonjs` you are telling `typescript` to transpile ES Modules into CommonJS `require`/`exports` syntax. CommonJS is notoriously hard to tree shake due to its dynamic nature, and most bundlers doesn't even try. If you set `esnext` however, this will leave `import`/`export` syntax intact so that webpack can take care of module resolution and tree shaking.

**Comment by nedtwigg** [comment] 2020-09-12 04:41
Thanks very much @alex996, sorry for making noise here, hope it was at least useful to others.  In the app we're using this on, changing the module to `esnext` basically cut our compiled size in half - improved a lot of things besides just react-feather.  I'm kinda curious why lodash and react-icons managed to get *some* shrinking done in our badly-configured environment, but not curious enough to dig further.  I'm gonna just take the solution and run!
